### ISSUE TITLE
How to craft expleding spears with artificer?

### ISSUE THREAD

**Issue by NeekoKun** [SchuhBaum/InfiniteSpears#3]
I am currently using the mod for carring more spears on my back as artificer but as I enable the mod I am unable to craft expleding spears. Is there an intended workaround?

**Comment by SchuhBaum** [comment]
The workaround goes as follows. Put the spear on your back. Then press and hold grab. Don't let go of grab. This does the following. You grab the spear from the back. Then you put it in your belly and create an explosive spear.

**Comment by NeekoKun** [comment]
Imma test it out asap, tyvm

**Comment by NeekoKun** [comment]
sorry it took a while but it worked!
